// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NostrGuestbook.Data;

#nullable disable

namespace NostrGuestbook.Data.Migrations
{
    [DbContext(typeof(GuestbookDb))]
    [Migration("20260930181212_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("NostrGuestbook.Data.Message", b =>
                {
                    b.Property<string>("PubKey")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(280)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("PubKey");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("NostrGuestbook.Data.Profile", b =>
                {
                    b.Property<string>("PubKey")
                        .HasColumnType("TEXT");

                    b.Property<long?>("FetchedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nip05")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Nip05Verified")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Picture")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("PubKey");

                    b.ToTable("Profiles");
                });
#pragma warning restore 612, 618
        }
    }
}
